# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "McNorton Blog"
description: > # this means to ignore newlines until "email:"
   A Jekyll theme - Medium inspired

email: mcnorton@gmail.com
#blog logo
logo: "/assets/images/mn_logo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/cA4aKEIPQrerBnp1yGHv_IMG_9534-3-2.jpg"

name: 'McNorton'
author: 'Taejung Lee'
author_image: "/assets/images/mn.jpg"

paginate:	5

url: "https://mcnorton.github.io" # the base hostname & protocol for your site
baseurl: ""
#used to display twitter cards
twitter_handle: '@mcnorton_'

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/mcnorton_
    desc: Follow me on twitter
#    share_url: http://twitter.com/share
#    share_title: ?text=
#    share_link: "&amp;url="

  - icon:	facebook
    url:	https://facebook.com/mcnorton.fb
    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/mcnorton
    desc:	
#    share_url:
#    share_title:
#    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
